server:
  port: 8982


#提供者
dubbo:
  application:
    name: springboot-provider
  registry:
    address: 192.168.25.135:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 8001
  scan:
    base-packages: com.ljh.provider
